[package]
name = "http-status-print"
version = "0.1.0"
authors = ["noah"]
description = "Utility to print explanatory information for http status codes"
homepage = "https://github.com/noahp/http-status-print"
repository = "https://github.com/noahp/http-status-print.git"
license = "MIT"

[dependencies]
clap = "2.31.1"
http = "0.1.5"

[profile.release]
lto = true
panic = 'abort'

